// Generated by CoffeeScript 1.12.7
(function() {
  var app, http, port;

  app = require('express')();

  http = require('http').Server(app);

  port = 3000;

  app.get('/', function(req, res) {
    return res.sendfile('index.html');
  });

  app.get('/about', function(req, res) {
    return res.sendfile('about.html');
  });

  app.get('/error', function(req, res) {
    res.status(404);
    return res.json('{"status":"404"}');
  });

  http.listen(port, function() {
    return console.log("listening on *:", port);
  });

}).call(this);
